# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5ea187c6e62a97afb236e31fb656b8725e9a641dce2c692dce1a225ea62fcca096b431d8807348b640fd8612d06697093fba40f1e43830d1510f04ec52f3450

test:
  secret_key_base: 76c58bf83f722b64eb761acd4a5f11fc6d0c082ca647c77a12536b463cc594303c743f1c9c0210459c3980e81fe2b5eccdb0e93b0d78c32f0d26d7f89ecd0b01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
